apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: frontend
bases:
  - ../base
resources:
  - storybook.yml
  - hpa.yml
patchesJson6902:
  - path: hostname.yml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: frontend
      version: v1
patchesStrategicMerge:
  - deployment.yml
  - configmap.yml
  - middleware-redirect-www.yml
