apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-www
spec:
  redirectRegex:
    regex: ^https?://dev\.atida\.com(.*)
    replacement: https://www.dev.atida.com$1
    permanent: true
