kind: Service
apiVersion: v1
metadata:
  name: storybook-service
  annotations:
    traefik.ingress.kubernetes.io/service.passhostheader: "false"
spec:
  ports:
    - name: http
      port: 80
  type: ExternalName
  externalName: storybook.dev.atidaplus.com.s3-website.eu-central-1.amazonaws.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storybook-ingress
  annotations:
    kubernetes.io/ingress.class: traefik-private
spec:
  rules:
    - host: storybook.dev.atida.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: storybook-service
                port:
                  name: http
