apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: frontend
resources:
  - deployment.yml
  - service.yml
  - middleware-redirect-www.yml
  - ingress.yml
  - pdb.yml
  - configmap.yml
secretGenerator:
  - name: frontend
    envs:
      - .env
generatorOptions:
  labels:
    generated: "true"
