export const Province = {
  A_CORUNA: 'A Coruña',
  ALVARA: 'Alava',
  ALBACETE: 'Albacete',
  ALICANTE: 'Alicante',
  ALMERIA: 'Almeria',
  ASTURIAS: 'Asturias',
  AVILA: 'Avila',
  BADAJOS: 'Badajoz',
  BALEARES: 'Baleares',
  BARCELONA: 'Barcelona',
  BURGOS: 'Burgos',
  CACERES: 'Caceres',
  CADIZ: 'Cadiz',
  CANTABRIA: 'Cantabria',
  CASTELLON: 'Castellon',
  CEUTA: 'Ceuta',
  CIUDAD_REAL: 'Ciudad Real',
  CORDOBA: 'Cordoba',
  CUENCA: 'Cuenca',
  GIRONA: 'Girona',
  GRANADA: 'Granada',
  GUADALAJARA: 'Guadalajara',
  GUIPUZCOA: 'Guipuzcoa',
  HUELVA: 'Huelva',
  HUESCA: 'Huesca',
  JAEN: 'Jaen',
  LA_RIOJA: 'La Rioja',
  LAS_PALMAS: 'Las Palmas',
  LEAON: 'Leon',
  LLEIDA: 'Lleida',
  LUGO: 'Lugo',
  MADRID: 'Madrid',
  MALAGA: 'Malaga',
  MELLILA: 'Melilla',
  MURCIA: 'Murcia',
  NAVARRA: 'Navarra',
  OURENSE: 'Ourense',
  PALENCIA: 'Palencia',
  PONTEVEDRA: 'Pontevedra',
  SALAMANCA: 'Salamanca',
  SANTA_CRUZ_DE_TENERIFE: 'Santa Cruz de Tenerife',
  SEGOVIA: 'Segovia',
  SEVILLA: 'Sevilla',
  SORIA: 'Soria',
  TARRAGONA: 'Tarragona',
  TERUEL: 'Teruel',
  TOLEDO: 'Toledo',
  VALENCIA: 'Valencia',
  VALLADOLID: 'Valladolid',
  VIZCAYA: 'Vizcaya',
  ZAMORA: 'Zamora',
  ZARAGOZA: 'Zaragoza'
}
Object.freeze(Province)
