// Unique feature flags
export enum FeatureFlag {
  THIRD_PARTY_SCRIPT_COOKIEPRO = '3rd-party-script.cookiePro',
  THIRD_PARTY_SCRIPT_EXPONEA = '3rd-party-script.exponea',
  THIRD_PARTY_SCRIPT_SPEEDCURVE = '3rd-party-script.speedcurve',
  THIRD_PARTY_SCRIPT_SEGMENT = '3rd-party-script.segment',
  THIRD_PARTY_SCRIPT_YOTPO = '3rd-party-script.yotpo',
  THIRD_PARTY_SCRIPT_NEW_RELIC = '3rd-party-script.newRelic',
  THIRD_PARTY_SCRIPT_NEW_RELIC_RECOMMENDED_IMPLEMENTATION = '3rd-party-script.newRelic.recommended-implementation',
  THIRD_PARTY_SCRIPT_GA_TRACKING_SCRIPT = '3rd-party-script.ga-tracking-script',
  THIRD_PARTY_SCRIPT_USE_NEXT_SCRIPT = '3rd-party-script.use-next-script',
  THIRD_PARTY_SCRIPT_CONSENT_MODE = '3rd-party-script.consent-mode',
  THIRD_PARTY_SCRIPT_RESKYT = '3rd-party-script.reskyt',
  THIRD_PARTY_SCRIPT_OPTIMIZELY = '3rd-party-script.optimizely',
  THIRD_PARTY_SCRIPT_LOAD_OPTIMIZELY_BEFORE_SEGMENT = '3rd-party-script.load-optimizely-before-segment',
  THIRD_PARTY_SCRIPT_RTB_HOUSE = '3rd-party-script.rtb-house',
  PRODUCT_IMAGE_ALLOW_ALTERNATIVE_FORMATS = 'product.image.allow-alternative-formats',
  PRODUCT_IMAGE_ALLOW_ALTERNATIVE_FORMATS_FOR_POP_LIST_VIEW_AND_AUTOCOMPLETE = 'product.image.allow-alternative-formats-for-POP-list-view-and-autocomplete',
  PRODUCT_IMAGE_WEBP_COMPRESSION = 'product.image.webp-compression',
  PRODUCT_IMAGE_AVIF_COMPRESSION = 'product.image.avif-compression',
  PRODUCT_PDP_PRODUCT_MEDIA_GALLERY = 'product.PDP.product-media-gallery',
  PRODUCT_PDP_PROMO_INFORMATION_BOX = 'product.PDP.promo-information-box',
  PRODUCT_BACK_IN_STOCK_ENABLED = 'product.PDP.back-in-stock-enabled',
  PRODUCT_PDP_SHOW_SAVINGS = 'product.PDP.show-savings',
  PRODUCT_PDP_ADD_TO_BASKET_CONTROLS_NEW_QUANTITY_SELECTOR = 'product.PDP.add-to-basket-controls.new-quantity-selector',
  PRODUCT_PDP_STICKY_ADD_TO_BASKET_CONTROLS = 'product.PDP.sticky-add-to-basket-controls',
  PRODUCT_PDP_SHOW_SCARCITY_MESSAGE = 'product.PDP.show-scarcity-message',
  PRODUCT_PDP_PRODUCT_SCARCITY_THRESHOLD = 'product.PDP.product-scarcity-threshold',
  PRODUCT_PDP_FETCH_SINGLE_BRAND = 'product.PDP.fetch-single-brand',
  PDP_ENABLE_HOTJAR_EVENT_TRIGGERS = 'pdp.enable-hotjar-event-triggers',
  PDP_ENABLE_EXPERT_SIGNATURE = 'product.PDP.expert-signature',
  PDP_ALL_NEW_PDP = 'pdp.all-new-pdp',
  ACCOUNT_LOYALTY_ATIDA_CASH = 'account.loyalty.atida-cash',
  ACCOUNT_LOYALTY_ATIDA_CASH_HISTORY = 'account.loyalty.atida-cash-history',
  ACCOUNT_LOYALTY_ATIDA_CASH_REWARDS = 'account.loyalty.atida-cash-rewards',
  ACCOUNT_LOYALTY_WELCOME_GIFT_RELEASE_DATE = 'account.loyalty.welcome-gift-release-date',
  ACCOUNT_FAVOURITES_HEADER_NAVIGATION = 'account.favourites.header-navigation',
  ACCOUNT_FAVOURITES_ALL_PAGES = 'account.favourites.all-pages',
  ACCOUNT_FAVOURITES_GUEST_FAVOURITES = 'account.favourites.guest-favourites',
  ACCOUNT_FAVOURITES_GRID_VIEW = 'account.favourites.grid-view',
  ACCOUNT_LOGIN_MIFARMA_BANNER = 'account.login.mifarma-banner',
  ACCOUNT_SALUTATION_FIELD = 'account.salutation-field',
  ACCOUNT_MARKETING_OPTION = 'account.marketing.option',
  ACCOUNT_MENU_NEW_MENU_STYLE = 'account.menu.new-menu-style',
  ACCOUNT_MENU_SOCIAL_LOGIN_AND_SIGNUP = 'account.menu.social-login-and-signup',
  ACCOUNT_SIGNUP_PROGRESS_BAR = 'account.signup.progress-bar',
  ACCOUNT_ADDRESS_VALIDATION = 'account.address-validation-threshold',
  ACCOUNT_ADDRESS_SUGGESTION_SIGNUP = 'account.address-suggestion.signup',
  ACCOUNT_ADDRESS_SUGGESTION_ADDRESS_BOOK = 'account.address-suggestion.address-book',
  ADDRESS_ADDRESS_ISO8601_DATE_FORMAT = 'address.ISO8601-date-format',
  ACCOUNT_CUSTOMER_CHECK = 'account.customer-check',
  ACCOUNT_EXPANDED_PASSWORD_POLICIES = 'account.expanded-password-policies',
  ACCOUNT_TWO_COLUMN_LOGIN_AND_SIGNUP = 'account.login.two-column-login-and-signup',
  ACCOUNT_HIDE_CONFIRM_PASSWORD_FIELD = 'account.hide-confirm-password-field',
  ACCOUNT_SOCIAL_LOGIN_AND_SIGNUP_GOOGLE = 'account.social-login-and-signup.google',
  ACCOUNT_SOCIAL_LOGIN_AND_SIGNUP_FACEBOOK = 'account.social-login-and-signup.facebook',
  ACCOUNT_SOCIAL_LOGIN_AND_SIGNUP_APPLE = 'account.social-login-and-signup.apple',
  ACCOUNT_DOWNLOAD_INVOICE = 'account.download-invoice',
  ACCOUNT_ACCESS_TOKEN_REFRESH = 'account.access-token.refresh',
  ACCOUNT_PHONE_TO_CUSTOMER_LEVEL = 'account.phone-to-customer-level',
  ACCOUNT_MULTIPLE_TAX_REGIONS_VALIDATION = 'account.multiple-tax-regions-validation',
  ACCOUNT_REQUEST_INVOICE = 'account.request-invoice',
  ACCOUNT_TRANSACTION_HISTORY_MOCKED_DATA = 'account.transaction-history.mocked-data',
  ACCOUNT_ADDITIONAL_CIF_FORMAT_VALIDATION = 'account.additional-cif-format-validation',
  ACCOUNT_DATE_OF_BIRTH = 'account.date-of-birth',
  CHECKOUT_ADDRESS_SUGGESTION = 'checkout.address-suggestion',
  CHECKOUT_PAYMENT_BIZUM = 'checkout.payment.bizum',
  CHECKOUT_PAYMENT_BRAINTREE_PAYMENT_METHOD_VISA_MASTER = 'checkout.payment.braintree.payment-method.visa-master',
  CHECKOUT_PAYMENT_SIBS_MULTIBANCO = 'checkout.payment.sibs.multibanco',
  CHECKOUT_PAYMENT_STRIPE_MULTIBANCO = 'checkout.payment.stripe-multibanco',
  CHECKOUT_PAYMENT_SIBS_MBWAY = 'checkout.payment.sibs.mbway',
  CHECKOUT_PAYMENT_BRAINTREE_PAYMENT_METHOD_PAYPAL = 'checkout.payment.braintree.payment-method.paypal',
  CHECKOUT_ADDRESS_BOOK_ADDRESS_SELECTOR = 'checkout.address-book.address-selector',
  CHECKOUT_MISSING_ADDRESS_FORM = 'checkout.missing-address-form',
  FILTER_SPECIAL_OFFER_BLACK_FRIDAY = 'filter.special-offer.black-friday',
  COUNTRY_SELECTOR_HEADER = 'country-selector-header',
  COOKIE_LOCALE_REDIRECTION = 'cookie-locale-redirection',
  LOCALE_REDIRECTION_BROWSER_PREFERENCES = 'locale-redirection-browser-preferences',
  LOCALE_REDIRECTION_HEADERS_FIX = 'locale-redirection-headers-fix',
  BROWSER_LOCALE_EXTERNAL_REDIRECTION = 'browser-locale-external-redirection',
  VIEWER_COUNTRY_EXTERNAL_REDIRECTION = 'viewer-country-external-redirection',
  VIEWER_COUNTRY_LOGGING = 'viewer-country-logging',
  FOOTER_COUNTRY_SELECTOR = 'footer-country-selector',
  FOOTER_TRUSTED_SHOPS = 'footer-trusted-shops',
  BASKET_FREE_SHIPPING_PRODUCTS = 'basket.free-shipping.products',
  TRANSLATIONS_ENABLE_API_PAGINATION = 'translations-enable-api-pagination',
  SEGMENT_SEARCH_AS_YOU_TYPE = 'segment.search-as-you-type',
  SEARCHBAR_RESULTS_TILES_ANCHOR_HREF_WITHOUT_LOCALE_FIX = 'searchbar.results-tiles.anchor-href-without-locale-fix',
  SEO_DISABLE_INDEXING = 'seo.disable-indexing',
  IMAGE_ALLOW_ALTERNATIVE_FORMATS = 'image.allow-alternative-formats',
  IMAGE_ALLOW_AVIF_FORMAT = 'image.allow-avif-format',
  IMAGE_ALLOW_AVIF_COMPRESSION = 'image.allow-avif-compression',
  IMAGE_ALLOW_WEBP_COMPRESSION = 'image.allow-webp-compression',
  IMAGE_ALLOW_JPEG_COMPRESSION = 'image.allow-jpeg-compression',
  IMAGE_ALLOW_DECODING_ASYNC = 'image.allow-decoding-async',
  IMAGE_USE_NEXT_IMAGE_COMPONENT = 'image.use-next-image-component',
  FETCH_PRIORITY = 'image.fetch-priority',
  ACCOUNT_MAKE_PHONE_NUMBER_FIELD_OPTIONAL = 'account.make-phone-number-field-optional',
  NAVIGATION_ADD_FILTER_AND_SORTING_PARAMETER_TO_URL = 'navigation.add-filter-and-sorting-parameters-to-url',
  NAVIGATION_UPDATE_PAGE_NUMBER_IN_URL_ON_PRODUCT_CLICK = 'navigation.update-page-number-in-url-on-product-click',
  CHECKOUT_PAYMENT_ORDER_PAYMENT_LOG_DATA = 'checkout.payment.order-payment.log-data',
  SEGMENT_SCRIPT_INTEGRATIONS_ALL_PROPERTY = 'segment.script.integrations.all-property',
  SEGMENT_SCRIPT_RETRY_INITIALIZATION = 'segment.retry-initialization',
  CHECKOUT_TERMS_AND_CONDITIONS = 'checkout.terms-and-conditions',
  BRAND_PAGE_CATEGORY_FILTERS = 'brand-page.category-filters',
  PROMOTION_OVERVIEW_PAGE_FILTERS_OR_FORMULA = 'promotion-overview-page.filters-or-formula',
  EXPERIMENT_PDP_SHOW_SAVING_PERCENTAGE = 'experiment.pdp.show-saving-percentage',
  CONTENTFUL_REPLACE_CDA_CALLS_WITH_WEBHOOKS = 'contentful.replace.cda-calls.with.webhooks',
  CONTENTFUL_FETCH_BRANDS_WITH_CDA = 'contentful.fetch-brands.cda',
  CONTENTFUL_REPLACE_CDA_MENU_CALL_WITH_PRE_NORMALIZED_JSON = 'contentful.replace-cda-menu-call-with-pre-normalized-json',
  CONTENTFUL_REPLACE_CDA_PAGE_REDIRECTS_NORMALIZED_JSON = 'contentful.replace-cda-page-redirects-normalized-json',
  CONTENTFUL_PAGE_SLUG_VALIDATION_WEBHOOK = 'contentful.page-slug-validation-webhook',
  NAVIGATION_STICKY_HEADER_MENU_ON_MOBILE = 'navigation.sticky-header-menu-on-mobile',
  NAVIGATION_STICKY_HEADER_MENU_ON_DESKTOP = 'navigation.sticky-header-menu-on-desktop',
  PDP_RECOMMENDATIONS_BLOCK_IS_UNDER_REVIEWS = 'pdp.recommendations-block.is-under-reviews',
  PDP_REVIEW_POLICY = 'pdp-review-policy',
  PRODUCT_QUANTITY_SELECTOR = 'core-shopping.product-quantity-selector',
  NAVIGATION_STICKY_FILTER_AND_SORT_BUTTON = 'navigation.sticky-filter-sort-button',
  BASKET_ADD_TO_BASKET_NOTIFICATION = 'basket.add-to-basket-notification',
  CHECKOUT_UNSUCCESSFUL_CANCEL_ORDER = 'checkout.unsuccessful.cancel-order',
  PRELOAD_LCP = 'assets.preload-lcp',
  PRELOAD_FONTS = 'assets.preload-fonts',
  PRECONNECT_TO_ASSETS = 'assets.preconnect',
  PRODUCT_LIST_PRODUCTS_PER_PAGE = 'product.list.products-per-page',
  CHECKOUT_PAYMENT_ADYEN_PAYMENT_METHODS = 'checkout.payment.adyen-payment-methods',
  FILTER_LIST_FILTERS_LIMIT = 'filter.list.filters-limit',
  FILTER_LIST_FILTERS_SHOW_MORE_LIMIT = 'filter.list.filters-show-more-limit',
  CHECKOUT_PAYMENT_ADYEN_GOOGLE_PAY = 'checkout.payment.adyen.google-pay',
  PDP_FREQUENTLY_BOUGHT_TOGETHER = 'product.frequently-bougth-together',
  PDP_SIMILAR_PRODUCTS = 'product.PDP.similar-products',
  BASKET_NOTIFICATION = 'basket.notification',
  NAVIGATION_ENABLE_AUTOCOMPLETE_DEBUG_MODE = 'navigation.enable-autocomplete-debug-mode',
  NAVIGATION_SCROLL_TO_TOP_BASKET_PAGE = 'navigation.scroll-to-top-on-basket-page',
  INTERACTIVE_PENCIL_BANNER = 'interactive-pencil-banner',
  CACHING_NEW_VALUES = 'caching.use-new-values',
  SEGMENT_PRODUCT_LIST_FILTERED_EVENT = 'segment-product-list-filtered-event',
  NAVIGATION_FIX_PRODUCT_POSITION_IN_SEARCH_AS_YOU_TYPE = 'navigation.fix-product-position-in-search-as-you-type-event',
  NAVIGATION_ADD_TYPE_BRANDPAGE_TO_CONTEXTRULES = 'navigation.add-type-brandpage-to-the-context-rules',
  THEME_CONFIG = 'theme-config',
  CHECKOUT_PAYMENT_ADYEN_APPLE_PAY = 'checkout.payment.adyen-apple-pay',
  CHECKOUT_PAYMENT_ADYEN_KLARNA_PAY_OVER_TIME = 'checkout.payment.adyen-klarna-pay-over-time',
  BASKET_PROMOTIONAL_ITEMS_PRICE_ZERO = 'basket.promotional-items.price-zero',
  SEO_GET_NO_INDEX_AND_NO_FOLLOW_TAGS_FROM_CONTENTFUL = 'navigation.get-no-index-and-no-follow-tags-from-contentful',
  PDP_TOOLTIP_PROMOTION_INFO = 'pdp.tooltip.promotion-info',
  SEO_FACILITATE_301_REDIRECTS = 'seo.facilitate-301-redirects',
  SEO_STRUCTURED_DATA_COP_AND_POP_BREADCRUMBS = 'seo.structured-data.cop-and-pop-breadcrumbs',
  CHECKOUT_HEADER_NAVIGATION_UPDATE_STYLE = 'checkout.header-navigation.update-style',
  ORDER_HISTORY_TRACKING = 'account.order-history.tracking-order',
  BASKET_ERROR_NOTIFICATION = 'basket.error-notification',
  MOBILE_ACCORDEON_REFINEMENT_LIST = 'mobile-accordeon-refinement-list',
  VOUCHER_CODES_NEW_DESIGN = 'voucher-blocks-homepage.new-design',
  CHECKOUT_PAYMENT_ADYEN_REQUESTED_TEST_ACQUIRER_RESPONSE_CODE = 'checkout.payment.adyen-requested-test-acquirer-response-code',
  ACCOUNT_COOKIE_EXPIRATION_TIMEOUT = 'account.cookie.expiration-timeout',
  PDP_LOYALTY_INFO = 'checkout.rewards',
  NAVIGATION_BREADCRUMBS_ON_POP_AND_COP = 'navigation.breadcrumbs-on-pop-and-cop',
  SEO_SHOW_COPY_CONTENT_ON_BRANDS_AND_PROMOTIONS_PAGES = 'seo.show-copy-content-on-brands-and-promotions-pages',
  ALGOLIA_PREVENT_ADDITIONAL_REQUEST_FROM_FETCHING_ALL_FACETS = 'algolia.prevent-additional-request-caused-by-fetching-all-filters-facets',
  CHECKOUT_PAYMENT_ADYEN_MB_WAY = 'checkout.payment.adyen-mbway',
  CHECKOUT_PAYMENT_ADYEN_MULTIBANCO = 'checkout.payment.adyen-multibanco',
  CHECKOUT_PAYMENT_ADYEN_CARD = 'checkout.payment.adyen-card',
  CHECKOUT_PAYMENT_ADYEN_SHOPPER_STATEMENT = 'checkout.payment.adyen-shopper-statement',
  LOYALTY_WELCOME_ATIDA_CASH_DISCOUNT_KEY = 'loyalty.welcome-atida-cash.discount-key',
  CHECKOUT_DELIVERY_MONDIAL_RELAY = 'checkout.delivery.mondial-relay',
  CHECKOUT_PAYMENT_ADYEN_APPLE_PAY_DISABLED_ON_LARGE_SCREEN = 'checkout.payment.adyen-apple-pay.disabled-on-large-screen',
  SEGMENT_REVERT_TRANSLATED_ROUTE = 'segment.revert-translated-route',
  CHECKOUT_PAYMENT_BRAINTREE_PAYMENT_METHOD_VISA_MASTER_3DS_V2 = 'checkout.payment.braintree.payment-method.visa-master.3ds-v2',
  BF_COUNTDOWN_PENCIL_BANNER = 'shopping.black-friday-pencil-banner',
  NEW_CAMPAIGN_FILTER = 'shopping.campaign-filter',
  NEW_CAMPAIGN_TAG_FILTER = 'shopping.campaign-tag-filter',
  CHECKOUT_DELIVERY_STICKY_CTA_BUTTON = 'checkout-delivery.sticky-cta-button',
  SHOPPING_SHOW_OUR_RECOMMENDATIONS_BEFORE_FBT = 'shopping.show-our-recommendations-before-fbt',
  PRODUCT_ON_DEMAND_INFO = 'shopping.on-demand-info',
  HIDE_FAKE_CATEGORIES_FROM_CATEGORY_FILTER = 'shopping.hide-fake-categories-from-category-filter',
  SHOW_LABELS_OVER_IMAGE_ON_PROMOTION_TEASER = 'shopping.promotion-teaser-labels-over-image',
  FIX_OVERLAPPING_LABELS_ON_FAVOURITES_PAGE = 'shopping.fix-overlapping-labels-on-favourites-page',
  FIX_PRODUCT_TILE_IMAGE_WIDTH = 'shopping.fix-product-tile-image-width',
  SEO_ADD_NOINDEX_TO_ON_DEMAND_PRODUCTS = 'seo.add-noindex-to-on-demand-products',
  PDP_IMPORTANT_INFO_COMPONENT = 'pdp.important-info-component',
  PDP_SELECTOR_GERMANY_PDP_TYPE = 'pdp.selector-germany-pdp-type',
  PDP_SHOW_GERMAN_PRODUCT_DETAILS = 'pdp.show-german-product-details',
  MULTICHANNEL_PRICES = 'multichannel-prices',
  MUTLICHANNEL_PRICES_MOCKED_BASKET = 'multichannel-prices.mocked-basket-channel',
  MUTLICHANNEL_PRICES_MOCKED_PRODUCT_PRICE_CHANNEL = 'multichannel-prices.mocked-product-price-channels',
  SHOW_DISCOUNT_LABELS_WITH_CAMPAIGN = 'shopping.show-discount-labels-together-with-campaign',
  BASKET_ADD_MULTIPLE_ITEMS = 'basket.add-multiple-items'
}

/* IMPORTANT: ONLY flags that will be evaluated on EVERY page view (see comment below)
 * i.e. any page that calls loadFeatureFlags from getServerSideProps
 */
export const allPagesFeatureFlags = [
  FeatureFlag.THIRD_PARTY_SCRIPT_COOKIEPRO,
  FeatureFlag.THIRD_PARTY_SCRIPT_EXPONEA,
  FeatureFlag.THIRD_PARTY_SCRIPT_SPEEDCURVE,
  FeatureFlag.THIRD_PARTY_SCRIPT_SEGMENT,
  FeatureFlag.THIRD_PARTY_SCRIPT_YOTPO,
  FeatureFlag.THIRD_PARTY_SCRIPT_NEW_RELIC,
  FeatureFlag.THIRD_PARTY_SCRIPT_NEW_RELIC_RECOMMENDED_IMPLEMENTATION,
  FeatureFlag.THIRD_PARTY_SCRIPT_GA_TRACKING_SCRIPT,
  FeatureFlag.THIRD_PARTY_SCRIPT_USE_NEXT_SCRIPT,
  FeatureFlag.THIRD_PARTY_SCRIPT_CONSENT_MODE,
  FeatureFlag.THIRD_PARTY_SCRIPT_RESKYT,
  FeatureFlag.THIRD_PARTY_SCRIPT_OPTIMIZELY,
  FeatureFlag.THIRD_PARTY_SCRIPT_LOAD_OPTIMIZELY_BEFORE_SEGMENT,
  FeatureFlag.THIRD_PARTY_SCRIPT_RTB_HOUSE,
  FeatureFlag.ACCOUNT_LOYALTY_ATIDA_CASH,
  FeatureFlag.ACCOUNT_FAVOURITES_GUEST_FAVOURITES,
  FeatureFlag.ACCOUNT_FAVOURITES_GRID_VIEW,
  FeatureFlag.ACCOUNT_FAVOURITES_HEADER_NAVIGATION,
  FeatureFlag.ACCOUNT_FAVOURITES_ALL_PAGES,
  FeatureFlag.ACCOUNT_LOGIN_MIFARMA_BANNER,
  FeatureFlag.ACCOUNT_MENU_NEW_MENU_STYLE,
  FeatureFlag.ACCOUNT_MENU_SOCIAL_LOGIN_AND_SIGNUP,
  FeatureFlag.ACCOUNT_EXPANDED_PASSWORD_POLICIES,
  FeatureFlag.ACCOUNT_SOCIAL_LOGIN_AND_SIGNUP_GOOGLE,
  FeatureFlag.ACCOUNT_SOCIAL_LOGIN_AND_SIGNUP_FACEBOOK,
  FeatureFlag.ACCOUNT_SOCIAL_LOGIN_AND_SIGNUP_APPLE,
  FeatureFlag.ACCOUNT_DOWNLOAD_INVOICE,
  FeatureFlag.ACCOUNT_ACCESS_TOKEN_REFRESH,
  FeatureFlag.ACCOUNT_PHONE_TO_CUSTOMER_LEVEL,
  FeatureFlag.ACCOUNT_REQUEST_INVOICE,
  FeatureFlag.ACCOUNT_ADDITIONAL_CIF_FORMAT_VALIDATION,
  FeatureFlag.ACCOUNT_DATE_OF_BIRTH,
  FeatureFlag.FILTER_SPECIAL_OFFER_BLACK_FRIDAY,
  FeatureFlag.COUNTRY_SELECTOR_HEADER,
  FeatureFlag.FOOTER_COUNTRY_SELECTOR,
  FeatureFlag.FOOTER_TRUSTED_SHOPS,
  FeatureFlag.SEGMENT_SEARCH_AS_YOU_TYPE,
  FeatureFlag.SEO_DISABLE_INDEXING,
  FeatureFlag.IMAGE_ALLOW_ALTERNATIVE_FORMATS,
  FeatureFlag.IMAGE_ALLOW_AVIF_FORMAT,
  FeatureFlag.IMAGE_ALLOW_AVIF_COMPRESSION,
  FeatureFlag.IMAGE_ALLOW_WEBP_COMPRESSION,
  FeatureFlag.IMAGE_ALLOW_JPEG_COMPRESSION,
  FeatureFlag.IMAGE_ALLOW_DECODING_ASYNC,
  FeatureFlag.IMAGE_USE_NEXT_IMAGE_COMPONENT,
  FeatureFlag.FETCH_PRIORITY,
  FeatureFlag.NAVIGATION_UPDATE_PAGE_NUMBER_IN_URL_ON_PRODUCT_CLICK,
  FeatureFlag.NAVIGATION_ADD_FILTER_AND_SORTING_PARAMETER_TO_URL,
  FeatureFlag.SEGMENT_SCRIPT_INTEGRATIONS_ALL_PROPERTY,
  FeatureFlag.SEGMENT_SCRIPT_RETRY_INITIALIZATION,
  FeatureFlag.CHECKOUT_TERMS_AND_CONDITIONS,
  FeatureFlag.NAVIGATION_STICKY_HEADER_MENU_ON_MOBILE,
  FeatureFlag.NAVIGATION_STICKY_HEADER_MENU_ON_DESKTOP,
  FeatureFlag.PRODUCT_QUANTITY_SELECTOR,
  FeatureFlag.NAVIGATION_STICKY_FILTER_AND_SORT_BUTTON,
  FeatureFlag.PRODUCT_IMAGE_ALLOW_ALTERNATIVE_FORMATS,
  FeatureFlag.PRODUCT_IMAGE_ALLOW_ALTERNATIVE_FORMATS_FOR_POP_LIST_VIEW_AND_AUTOCOMPLETE,
  FeatureFlag.PRODUCT_IMAGE_WEBP_COMPRESSION,
  FeatureFlag.PRODUCT_IMAGE_AVIF_COMPRESSION,
  FeatureFlag.BASKET_ADD_TO_BASKET_NOTIFICATION,
  FeatureFlag.PRELOAD_LCP,
  FeatureFlag.PRELOAD_FONTS,
  FeatureFlag.PRECONNECT_TO_ASSETS,
  FeatureFlag.PRECONNECT_TO_ASSETS,
  FeatureFlag.PRELOAD_FONTS,
  FeatureFlag.PRODUCT_LIST_PRODUCTS_PER_PAGE,
  FeatureFlag.PDP_ENABLE_HOTJAR_EVENT_TRIGGERS,
  FeatureFlag.PDP_ENABLE_EXPERT_SIGNATURE,
  FeatureFlag.PDP_REVIEW_POLICY,
  FeatureFlag.PDP_ALL_NEW_PDP,
  FeatureFlag.BASKET_NOTIFICATION,
  FeatureFlag.FILTER_LIST_FILTERS_LIMIT,
  FeatureFlag.FILTER_LIST_FILTERS_SHOW_MORE_LIMIT,
  FeatureFlag.NAVIGATION_ENABLE_AUTOCOMPLETE_DEBUG_MODE,
  FeatureFlag.INTERACTIVE_PENCIL_BANNER,
  FeatureFlag.SEGMENT_PRODUCT_LIST_FILTERED_EVENT,
  FeatureFlag.NAVIGATION_FIX_PRODUCT_POSITION_IN_SEARCH_AS_YOU_TYPE,
  FeatureFlag.SEO_GET_NO_INDEX_AND_NO_FOLLOW_TAGS_FROM_CONTENTFUL,
  FeatureFlag.THEME_CONFIG,
  FeatureFlag.SEO_GET_NO_INDEX_AND_NO_FOLLOW_TAGS_FROM_CONTENTFUL,
  FeatureFlag.ORDER_HISTORY_TRACKING,
  FeatureFlag.MOBILE_ACCORDEON_REFINEMENT_LIST,
  FeatureFlag.VOUCHER_CODES_NEW_DESIGN,
  FeatureFlag.SEO_STRUCTURED_DATA_COP_AND_POP_BREADCRUMBS,
  FeatureFlag.MOBILE_ACCORDEON_REFINEMENT_LIST,
  FeatureFlag.ACCOUNT_COOKIE_EXPIRATION_TIMEOUT,
  FeatureFlag.NAVIGATION_BREADCRUMBS_ON_POP_AND_COP,
  FeatureFlag.SEO_SHOW_COPY_CONTENT_ON_BRANDS_AND_PROMOTIONS_PAGES,
  FeatureFlag.ALGOLIA_PREVENT_ADDITIONAL_REQUEST_FROM_FETCHING_ALL_FACETS,
  FeatureFlag.SEGMENT_REVERT_TRANSLATED_ROUTE,
  FeatureFlag.BF_COUNTDOWN_PENCIL_BANNER,
  FeatureFlag.CONTENTFUL_REPLACE_CDA_CALLS_WITH_WEBHOOKS,
  FeatureFlag.CONTENTFUL_PAGE_SLUG_VALIDATION_WEBHOOK,
  FeatureFlag.NEW_CAMPAIGN_FILTER,
  FeatureFlag.HIDE_FAKE_CATEGORIES_FROM_CATEGORY_FILTER,
  FeatureFlag.SHOW_LABELS_OVER_IMAGE_ON_PROMOTION_TEASER,
  FeatureFlag.FIX_OVERLAPPING_LABELS_ON_FAVOURITES_PAGE,
  FeatureFlag.FIX_PRODUCT_TILE_IMAGE_WIDTH,
  FeatureFlag.MUTLICHANNEL_PRICES_MOCKED_PRODUCT_PRICE_CHANNEL,
  FeatureFlag.SHOW_DISCOUNT_LABELS_WITH_CAMPAIGN,
  FeatureFlag.SEARCHBAR_RESULTS_TILES_ANCHOR_HREF_WITHOUT_LOCALE_FIX
]

/* NOTE: As evaluating a flag(s) reports the flag(s) statistics back to the feature flag service,
 * if a flag is only used on a single page or group of pages (not all pages),
 * then please pass the flag into loadFeatureFlags from getServerSideProps.
 * Create and export groups of feature flags for groups of pages below if needed.
 */

/* Example Groupings */

/* IDEAS (WIP for the team) for how we might group together pages that need a set of feature flags evaluating for them
 * then pass these to loadFeatureFlags from getServerSideProps in these pages.
 */

/* Features that are only displayed in the my account pages */
// export const myAccountPagesFeatureFlags = [
//   FeatureFlag.MY_ACCOUNT_PAGES_FEATURE_1,
//   FeatureFlag.MY_ACCOUNT_PAGES_FEATURE_2,
//   FeatureFlag.MY_ACCOUNT_PAGES_FEATURE_3
// ]

/* Features Any feature flag that is used in the full page layout (head, footer, navigation)
 * and not in the minimal page layout etc
 */
// export const fullPageLayoutFeatureFlags = [
//   FeatureFlag.FAVOURITES,
//   FeatureFlag.ANOTHER_FEATURE
// ]
