apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: frontend
bases:
  - ../base
resources:
  - hpa.yml
patchesStrategicMerge:
  - ingress.yml
  - deployment.yml
  - configmap.yml
